# Legendary Weapons Configuration
# All cooldowns are in seconds

items:
  cosmic_katana:
    display_name: "&bCosmic Katana"
    material: NETHERITE_SWORD
    cooldown: 10
    dash_damage: 8.0
    dash_distance: 4.0
    dash_duration: 10 # ticks

  thunder_striker:
    display_name: "&bThunder Striker"
    material: NETHERITE_AXE
    min_fall_distance: 16
    damage_multiplier: 1.0
    explosion_radius: 2.0

  star_staff:
    display_name: "&bStar Staff"
    material: BLAZE_ROD
    cooldown: 20
    projectile_speed: 1.3
    projectile_lifetime: 60 # ticks
    explosion_damage: 14.0
    explosion_radius: 8.0

  earth_wand:
    display_name: "&bEarth Wand"
    material: STICK
    cooldown: 30
    radius: 10
    duration: 300 # ticks (15 seconds)
    resistance_duration: 200 # ticks (10 seconds)
    resistance_level: 2

  poseidons_trident:
    display_name: "&bPoseidon's Trident"
    material: TRIDENT
    cooldown: 10
    normal_launch_multiplier: 2
    water_launch_multiplier: 5
    vertical_boost: 1.5

  ice_bow:
    display_name: "&bIce Bow"
    material: BOW
    freeze_chance: 0.3
    freeze_duration: 60 # ticks (3 seconds)
    freeze_level: 1

  dragon_wings:
    display_name: "&bDragon Wings"
    material: ELYTRA
    cooldown: 30
    charge_time: 5 # seconds
    vertical_boost: 3.0

  lich_staff:
    display_name: "&bLich Staff"
    material: BONE
    cooldown: 120
    skeleton_count: 3
    skeleton_lifetime: 1200 # ticks (60 seconds)

  calling_of_the_warden:
    display_name: "&bCalling of the Warden"
    material: NETHER_STAR
    cooldown: 60
    zombie_health: 40
    zombie_lifetime: 1200 # ticks (60 seconds)

gods_greataxe:
  display_name: "&bGod's Greataxe"
  material: NETHERITE_AXE
  base_damage: 18
  critical_multiplier: 1.5
  knockback_multiplier: 1.2
  vertical_knockback: 0.4
  sweep_radius: 3.0
  sweep_damage: 1.0
  attribute_modifiers:
    attack_damage: 10.0
    attack_speed: -4

  speed_daggers:
    display_name: "&bSpeed Daggers"
    material: IRON_SWORD
    base_damage: 6
    haste_level: 4
    bypass_immunity: true

  enhancement_orb:
    display_name: "&bEnhancement Orb"
    material: NETHERITE_INGOT
    absorption_threshold: 10 # health
    absorption_cooldown: 60 # seconds
    absorption_duration: 400 # ticks (20 seconds)
    absorption_level: 2
    speed_duration: 100 # ticks (5 seconds)
    speed_level: 1
    jump_duration: 100 # ticks (5 seconds)
    jump_level: 1

  life_drainer:
    display_name: "&bLife Drainer"
    material: IRON_SWORD
    heal_amount: 1.0
    require_critical: true

  magic_sack:
    display_name: "&bMagic Sack of Legend"
    material: BUNDLE
    possible_items:
      - "cosmic_katana"
      - "thunder_striker"
      - "star_staff"
      - "earth_wand"
      - "poseidons_trident"
      - "ice_bow"
      - "dragon_wings"
      - "lich_staff"
      - "calling_of_the_warden"
      - "gods_greataxe"
      - "speed_daggers"
      - "enhancement_orb"
      - "life_drainer"

# Sound Effects
sounds:
  ability_use: ENTITY_PLAYER_LEVELUP
  ability_cooldown: BLOCK_NOTE_BLOCK_BASS
  teleport: ENTITY_ENDERMAN_TELEPORT
  explosion: ENTITY_GENERIC_EXPLODE
  freeze: BLOCK_GLASS_BREAK
  heal: ENTITY_EXPERIENCE_ORB_PICKUP

# Particle Effects
particles:
  ability_use: END_ROD
  damage: DAMAGE_INDICATOR
  critical: CRIT
  explosion: EXPLOSION_NORMAL
  freeze: SNOWFLAKE
  heal: HEART

# Messages
messages:
  cooldown: "&cAbility on cooldown. %seconds%s remaining."
  sack_reward: "&dThe magic sack contained: %item%"
  enhancement_activate: "&6Enhancement Orb activates, protecting you!"
  summon_skeletons: "&5You summon skeletons to fight for you!"
  summon_warden: "&5You summon a warden's minion to fight for you!"
  dragon_wings_ground: "&cYou must be on the ground to use Dragon Wings."
  gods_axe: "&6You feel the power of the gods in your hands!"