name: LegendaryWeapons
version: 1.0
main: LegendaryWeapons.legendaryWeapons.LegendaryWeapons
api-version: "1.21"
authors: [Oddrot09]
description: Adds legendary weapons with special abilities
website: none
depend: [ProtocolLib]

commands:
  giveitem:
    description: Gives a legendary weapon to a player
    usage: /giveitem <player> <item>
    permission: legendaryweapons.give
    permission-message: "&cYou don't have permission to use this command!"
    aliases: [giveweapon, lwgive]